apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: satyamsonker1010/auth-service-test:latest
          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: auth-server-config
            - secretRef:
                name: auth-server-secret

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1500m"
              memory: "1Gi"

          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=512"
